changelog:
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
        - feat
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🏗️ CI & Build
      labels:
        - ci
        - build
    - title: 📖 Documentation
      labels:
        - documentation
        - docs
    - title: 🔧 Other Changes
      labels:
        - "*"
  exclude:
    labels:
      - skip-changelog
